#!/bin/bash
#
# Everything that has to exist before XcodeGen can generate the project.
#
# This file exists because the same two steps were written out three times —
# once in Scripts/local-build.sh, once in build-ipa.yml, once in
# screenshots.yml — and the three copies drifted. The icon-catalog step opens
# with `rm -rf Generated`; the stamp step writes into `Generated`. Get that
# order wrong and the stamp is deleted a second after it is written, and the
# compiler fails with four `cannot find 'BuildInfo' in scope` errors.
#
# That is exactly what happened in dc845b3: the local script had the right
# order, both workflows had the wrong one, local builds stayed green, and CI
# produced no IPA at all.
#
# So there is now one copy of the order, and everything calls it.
#
#   ./Scripts/prepare-build.sh            stamp from HEAD
#   ./Scripts/prepare-build.sh --local    stamp from HEAD, marked "+local" if dirty
#
# Run from the repository root.

set -euo pipefail

LOCAL=0
[ "${1:-}" = "--local" ] && LOCAL=1

CATALOG="Generated/Assets.xcassets"

# --- 1. The asset catalog ----------------------------------------------------
# The app icon is built here rather than committed as a folder of JSON. Asset
# catalogs are fiddly to upload correctly from a phone, so all the repository
# needs is the PNG — anywhere in the tree — and this makes the rest.
rm -rf Generated
mkdir -p "$CATALOG/AppIcon.appiconset"
printf '{\n  "info" : { "author" : "xcode", "version" : 1 }\n}\n' > "$CATALOG/Contents.json"

ICON=$(find . -path ./.git -prune -o -name 'AppIcon-1024.png' -print 2>/dev/null | head -1)
if [ -n "$ICON" ]; then
  echo "Using icon: $ICON"
  cp "$ICON" "$CATALOG/AppIcon.appiconset/AppIcon-1024.png"
  cat > "$CATALOG/AppIcon.appiconset/Contents.json" <<'JSON'
{
  "images" : [
    {
      "filename" : "AppIcon-1024.png",
      "idiom" : "universal",
      "platform" : "ios",
      "size" : "1024x1024"
    }
  ],
  "info" : { "author" : "xcode", "version" : 1 }
}
JSON
else
  echo "No AppIcon-1024.png found — building without an icon."
  printf '{\n  "images" : [],\n  "info" : { "author" : "xcode", "version" : 1 }\n}\n' \
    > "$CATALOG/AppIcon.appiconset/Contents.json"
fi

# --- 2. The build stamp ------------------------------------------------------
# Four successful IPA builds landed within an hour once, and there was no way to
# tell from the running app which one was on the phone. Now Settings → About
# says. Written *after* the catalog, because the catalog step deletes Generated.
SHA=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
SUBJECT=$(git log -1 --pretty=%s 2>/dev/null | tr -d '"' | cut -c1-60)
DIRTY=""
if [ "$LOCAL" = "1" ]; then
  git diff --quiet 2>/dev/null || DIRTY=" +local"
fi

cat > Generated/BuildInfo.swift <<SWIFT
// Generated by Scripts/prepare-build.sh. Do not edit, do not commit.
enum BuildInfo {
    static let commit = "${SHA}${DIRTY}"
    static let subject = "${SUBJECT}"
    static let builtAt = "$(date -u '+%Y-%m-%d %H:%M UTC')"
}
SWIFT

# --- 3. Say so loudly if either half is missing ------------------------------
# A missing file here is four compiler errors and a wasted CI run otherwise.
for required in "$CATALOG/Contents.json" \
                "$CATALOG/AppIcon.appiconset/Contents.json" \
                "Generated/BuildInfo.swift"; do
  if [ ! -f "$required" ]; then
    echo "✗ prepare-build: $required was not produced — the build would fail later, confusingly."
    exit 1
  fi
done

find Generated -type f | sort
